Specify tests' location
in CI got:
ImportError: cannot import name 'escape' from 'html'
(/home/runner/work/PyABC2/PyABC2/pyabc2/abcjs/html/__init__.py)

which is used in Norbeck, but also by anywidget deps, it looks like in
the tb